### PR TITLE
Attempt transition R-3.6.1

### PR DESCRIPTION
**Pull request by auberginekenobi**

### CODE REVIEW

**Comment by bahill** [comment]
@auberginekenobi is this still something you'd like to see accepted as a Pull Request

**Comment by auberginekenobi** [comment]
@bahill wow, it's been two years since I looked at this repo. I would say yes, I think it's a good idea to update R from 2.x.x; but it looks like the docker CI test failed. @edjuaro I think you helped me update this repo, how would we go about checking what would break if we merged?

**Comment by bahill** [comment]
Since this is no longer how we are maintaining Dockerfiles, we're closing this, archiving the repo, and putting a note in the MethylationCNV repo

**Comment by bahill** [comment]
PS - we already updated, so this really is null (https://github.com/genepattern/MethylationCNVAnalysis)

**Comment by bahill** [comment]
This must have been done locally - as this is the repo for the Dockerfile used to create the Docker image used by MethylationCNV. Still old - so let's leave it be for now and come back to it when we need to.

**Pull request closed without merging**
